siteTitle = "defcon402"
siteDescr = "Security in the midwest."
siteAuthor = "Adam Schaal"

siteTwitterUrl = "https://twitter.com/defcon402"
siteGithubUrl = "https://github.com/DEFCON402/DEFCON402.github.io"
sitelinkedInUrl = "#"
siteEmailUrl = "adam@dc402.org"
siteFacebookUrl = "#"
siteYouTubeUrl = "#"

googleAnalyticsId = "UA-109234778-1"

linkPrefix="/hatsec.github.io"